version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: event_processing_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-network

  # NATS JetStream
  nats:
    image: nats:2.10-alpine
    command: ["-js", "-m", "8222"]
    ports:
      - "4223:4222"
      - "8223:8222"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-network

  # Publisher (External service)
  publisher:
    image: andriiuni/events
    environment:
      EVENT_ENDPOINT: http://gateway:3000/webhook/events
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - event-network

  # Gateway Service
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    environment:
      PORT: 3000
      NATS_URL: nats://nats:4222
    ports:
      - "3000:3000"
    depends_on:
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-network

  # Facebook Collector
  fb-collector:
    build:
      context: .
      dockerfile: services/fb-collector/Dockerfile
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/event_processing_dev
      NATS_URL: nats://nats:4222
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-network

  # TikTok Collector
  ttk-collector:
    build:
      context: .
      dockerfile: services/ttk-collector/Dockerfile
    environment:
      PORT: 3002
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/event_processing_dev
      NATS_URL: nats://nats:4222
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-network

  # Reporter Service
  reporter:
    build:
      context: .
      dockerfile: services/reporter/Dockerfile
    environment:
      PORT: 3003
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/event_processing_dev
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-network

volumes:
  postgres_dev_data:

networks:
  event-network:
    driver: bridge
